groups:
  - name: FailureAlerts
    rules:

      - alert: FailureRate
        expr: sum(rate(failure_total{persistent="n"}[1m])) by(service, category) > 1
        for: 5s
        labels:
          severity: page
        annotations:
          summary: "Service {{ $labels.service }} has a high failure rate"
          description: "{{ $labels.service }} has had more than 1 {{ $labels.category }} failure per minute in the last 5 seconds."
